@startuml
rectangle "CIRCUIT-SAT" as CIRCUIT_SAT
rectangle SAT 
rectangle "3-CNF-SAT" as 3_CNF_SAT 
rectangle "CLIQUE" as CLIQUE
rectangle "VERTEX-COVER" as VERTEX_COVER
rectangle "HAM-CYCLE" as HAM_CYCLE
rectangle "SUBSET-SUM" as SUBSET_SUM
rectangle "SET-COVER" as SET_COVER
rectangle "TSP" as TSP
rectangle "INDEPENDENT-SET" as INDEPENDENT_SET
rectangle "DIR-HAM-CYCLE" as DIR_HAM_CYCLE
rectangle "KNAPSTACK" as KNAPSTACK

CIRCUIT_SAT -down-> SAT #red
SAT -down-> 3_CNF_SAT  #red
3_CNF_SAT-> CLIQUE #green
SUBSET_SUM <- 3_CNF_SAT #red
KNAPSTACK <- SUBSET_SUM #red
CLIQUE -> VERTEX_COVER #green
CLIQUE <- VERTEX_COVER #green
INDEPENDENT_SET -> CLIQUE #green
INDEPENDENT_SET <- CLIQUE #green
VERTEX_COVER -> HAM_CYCLE #green
VERTEX_COVER -down-> SET_COVER #green
HAM_CYCLE -> TSP #red
3_CNF_SAT -> HAM_CYCLE  #red
3_CNF_SAT -> VERTEX_COVER  #green
3_CNF_SAT -> TSP  #red
3_CNF_SAT -down-> INDEPENDENT_SET #green
INDEPENDENT_SET -> VERTEX_COVER #green
3_CNF_SAT -> DIR_HAM_CYCLE #red
DIR_HAM_CYCLE -> HAM_CYCLE #red
@enduml
